name: CI

on:
  push:
    #branches: [ ci ]
    tags:
      - 'v.*.*.*'
      - ci

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Otherwise `git describe --tags` doesn't work

      - uses: actions/checkout@v2
        with:
          repository: son-link/CD-Tray
          path: cdtray

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt-get install -yq fuse dh-virtualenv devscripts debhelper python3-setuptools ython3-pyqt5 python3-gst-1.0 python3-psutil

      - name: Create AppImage
        run: |
          # Build AppImage
          ARCH=$(uname -m)
          VERSION=$(git describe --tags --always)
          ./build-appimage.sh

      - name: Create deb package
        run: |
          ARCH=$(uname -m)
          VERSION=$(git describe --tags --always)
          debuild -b -us -uc

      - name: Archive AppImage
        uses: actions/upload-artifact@v2
        with:
          name: AppImage
          path: CD-Tray-*.AppImage

      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage CD-Tray-*.AppImage
          ./pyuploadtool-x86_64.AppImage *.deb
