name: Make deb packages

on:
  push:
    #branches: [ ci ]
    tags:
      - 'v.*.*.*'
      - ci

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_py311:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Otherwise `git describe --tags` doesn't work

      - uses: actions/checkout@v2
        with:
          repository: son-link/CD-Tray
          path: cdtray

      - name: Install dependencies
        run: |
          sudo apt update && sudo apt-get install -yq rename
      
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps: python3-setuptools python3-pyqt5 python3-gst-1.0 python3-psutil python3-dbus.mainloop.pyqt5 dh-python python3-gi rename

      - name: Rename package
        run:  |
          cd debian/artifacts/
          rename 's/.deb/\-python3.11.deb/i' *.deb

      - name: Upload deb package
        uses: actions/upload-artifact@v3
        with:
          name: debian12
          path: debian/artifacts/cdtray_2.0.0-python3.11_all.deb

  upload:
    runs-on: ubuntu-latest
    needs: [build_py311]
    steps:
      - name: Download deb result for job 1
        uses: actions/download-artifact@v3
        with:
          name: debian12
    
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt-get install -yq fuse
          
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage cdtray_*.deb
