name: Make deb packages

on:
  push:
    #branches: [ ci ]
    tags:
      - 'v.*.*.*'
      - ci

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build_py311:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Otherwise `git describe --tags` doesn't work

      - uses: actions/checkout@v2
        with:
          repository: son-link/CD-Tray
          path: cdtray
      
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps: python3-setuptools python3-pyqt5 python3-gst-1.0 python3-psutil python3-dbus.mainloop.pyqt5 dh-python python3-gi

      - name: Rename package
        run:  |
          cp debian/artifacts/cdtray_2.0.0_all.deb cdtray_2.0.0-python3.11_all.deb 

      - name: Upload deb package
        uses: actions/upload-artifact@v3
        with:
          name: debian12
          path: cdtray_2.0.0-python3.11_all.deb

  build_py310:
    runs-on: ubuntu-lastet
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Otherwise `git describe --tags` doesn't work

      - uses: actions/checkout@v2
        with:
          repository: son-link/CD-Tray
          path: cdtray
      
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          docker-image: ubuntu:22.04
          buildpackage-opts: --build=binary --no-sign
          extra-build-deps: python3-setuptools python3-pyqt5 python3-gst-1.0 python3-psutil python3-dbus.mainloop.pyqt5 dh-python python3-gi

      - name: Rename package
        run:  |
          cp debian/artifacts/cdtray_2.0.0_all.deb cdtray_2.0.0-python3.10_all.deb 

      - name: Upload deb package
        uses: actions/upload-artifact@v3
        with:
          name: python310
          path: cdtray_2.0.0-python3.10_all.deb


  upload:
    runs-on: ubuntu-latest
    needs: [build_py311, build_py310 ]
    steps:
      - name: Download deb result for job 1
        uses: actions/download-artifact@v3
        with:
          name: debian12

      - name: Download deb result for job 1
        uses: actions/download-artifact@v3
        with:
          name: python310
        
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt-get install -yq fuse
          
      - name: Create release and upload artifacts
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          wget -q https://github.com/TheAssassin/pyuploadtool/releases/download/continuous/pyuploadtool-x86_64.AppImage
          chmod +x pyuploadtool-x86_64.AppImage
          ./pyuploadtool-x86_64.AppImage cdtray_*.deb
