name: Make deb packages

on:
  push:
    #branches: [ ci ]
    tags:
      - 'v.*.*.*'
      - ci

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Otherwise `git describe --tags` doesn't work

      - uses: actions/checkout@v2
        with:
          repository: son-link/CD-Tray
          path: cdtray
          
      - name: Install dependencies
        run: |
          sudo apt update && sudo apt-get install -yq fuse devscripts debhelper python3-setuptools python3-pyqt5 python3-gst-1.0 python3-psutil python3-dbus.mainloop.pyqt5 dh-python python3-gi rename
          
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: --build=binary --no-sign
